### ISSUE TITLE
dummy variables for categories

### ISSUE THREAD

**Issue by zbuckley** [nuisanceparameters/project-2#5]
build factor variables (yes/no) for all columns ending in _categories, and for the genres. 

in pandas... apparently it's called dummy variables.

**Comment by seanpili** [comment]
The Code Has been pushed. Two things to think about. 

1: I excluded any categories that AT LEAST one film hadn't been nominated for AND won in the dataset... I can change it to include nominated OR won with a simple replace-all statement... 

2: Brian Said we might want to reduce all of the non-oscar awards into two variables.... # of nominations and # of wins... or maybe a ratio of wins to nominations of non-oscar awards... so I can create those variables too

**Comment by PedroUria** [comment]
About number 2, we already have those. They are awards_wins and awards_nominations. But yeah, they might become a bit different if you compute them using the dummy variables for categories, so it is worth a try.
